INPUT = 366


def spinlock(steps, insertions=2017):
    """Return the list generated by a spinlock."""
    buff = [0]
    index = 0
    for value in range(1, insertions + 1):
        index = (index + steps) % len(buff) + 1
        buff.insert(index, value)
    return buff


def main():
    buff = spinlock(INPUT)
    print("Part 1:", buff[buff.index(2017) + 1])


if __name__ == "__main__":
    main()
